pipelines:
  - name: pipelineApproval
    configuration:
      nodePool: default-dynamic-nodepool
    steps:
      - name: step1
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - bob
        execution:
          onExecute:
            - echo "Hello World"
